### PR TITLE
Better English messages

### PR DESCRIPTION
**Pull request by gregariomansa**
I have rewritten some English text in the code. All the modified files are from language/en . The modified files are ingame.php, tech.php and FAQ.php . The modifications are only in the English messages. I have made no change in the actual code.

### CODE REVIEW

**Comment by mys** [comment]
Thank You for contribution. Good job!

**Comment by gregariomansa** [comment]
Thank you for receiving my contribution. I understand you have included the
changes, but I don't see them in the game. For example, in the Overview
window, in the Active Admins line, I still see "no any online
administrator", instead of "no administrator online". Can you comment on
this? I have more English improvements that I'd like to do, but I will wait
until I actually see the changes I have already made.

2018-02-08 4:55 GMT-03:00 mys <notifications@github.com>:

**Comment by mys** [comment]
@fervi has to update the files on the game server

**Comment by gregariomansa** [comment]
I see the changes now! Thanks. I'll keep sending the English improvements.

2018-02-08 5:37 GMT-03:00 mys <notifications@github.com>:

**Pull request merged**
