### PR TITLE
time reduction each level of jumpgate

### PR DESCRIPTION
**Pull request by Qwatayean**
Tried to create an approximate formula to the http://owiki.de/index.php/Sprungtor#Cooldown-Zeit and seems this one is similar

### CODE REVIEW

**Comment by mys** [comment]
Why 0.05 multiplier? Isn't 0.1 more approximate? Each level of jumpgate cuts cooling time by ~10%.
Would be nice to take into account universe speed too.

**Comment by Qwatayean** [comment]
I tried to find a value that could be balanced, so used 0.05 as a preview. Was expecting a comment so I could change it after :)

It depends of how faster you want the game, and which speed should use, global speed or fleet speed? 

Tried to google translate the wiki, but the translation was awful

**Comment by mys** [comment]
>which speed should use, global speed or fleet speed

Good point. The wiki isn't precise enough. Let's stick to global speed then?

**Comment by Qwatayean** [comment]
Yes. Seems the best solution

**Pull request closed without merging**
